export const EVENTS = {
  DRAWER_CLOSE: 'drawer-close',
  DRAWER_OPEN: 'drawer-open',
  DRAWER_TOGGLE: 'drawer-toggle',
  MODAL_CLOSE: 'modal-close',
  MODAL_OPEN: 'modal-open',
  MODAL_TOGGLE: 'modal-toggle',
  SPINBUTTON_CHANGE: 'spinbutton-change',
  DISCLOSURE_BUTTON_OPEN: 'disclosure-button:open',
  DISCLOSURE_BUTTON_CLOSE: 'disclosure-button:close',
  SWITCH_ACTIVATE: 'switch:activate',
  SWITCH_DEACTIVATE: 'switch:deactivate',
  ACCORDION_PANEL_OPEN: 'accordion-panel:open',
  ACCORDION_PANEL_CLOSE: 'accordion-panel:close',
  COMBOBOX_LOADING: 'combobox:loading',
  COMBOBOX_LOADED: 'combobox:loaded',
  COMBOBOX_UPDATE: 'combobox:update',
  COMBOBOX_SUBMIT: 'combobox:submit',
  COMBOBOX_EMPTY: 'combobox:empty',
  WINDOWSPLITTER_CHANGE: 'windowsplitter:change',
  TAB_BEFORE_ACTIVATE: 'tab-before-activate',
  TAB_ACTIVATE: 'tab-activate',
  TAB_DELETE: 'tab-delete',
  CART_BEFORE_ADD: 'cart-before-add',
  CART_BEFORE_UPDATE: 'cart-before-update',
  CART_UPDATE: 'cart-update',
  VARIANT_CHANGE: 'variant-change',
};

export type EventNames = typeof EVENTS[keyof typeof EVENTS];