export const EVENTS = {
  DRAWER_BEFORE_CLOSE: 'drawer:before-close',
  DRAWER_BEFORE_OPEN: 'drawer:before-open',
  DRAWER_CLOSE: 'drawer:close',
  DRAWER_OPEN: 'drawer:open',
  DRAWER_TOGGLE: 'drawer:toggle',
  MODAL_BEFORE_CLOSE: 'modal:before-close',
  MODAL_BEFORE_OPEN: 'modal:before-open',
  MODAL_CLOSE: 'modal:close',
  MODAL_OPEN: 'modal:open',
  MODAL_TOGGLE: 'modal:toggle',
  SPINBUTTON_CHANGE: 'spinbutton:change',
  DISCLOSURE_BUTTON_OPEN: 'disclosure-button:open',
  DISCLOSURE_BUTTON_CLOSE: 'disclosure-button:close',
  SWITCH_ACTIVATE: 'switch:activate',
  SWITCH_DEACTIVATE: 'switch:deactivate',
  ACCORDION_OPEN: 'accordion:open',
  ACCORDION_CLOSE: 'accordion:close',
  COMBOBOX_LOADING: 'combobox:loading',
  COMBOBOX_LOADED: 'combobox:loaded',
  COMBOBOX_UPDATE: 'combobox:update',
  COMBOBOX_SUBMIT: 'combobox:submit',
  COMBOBOX_EMPTY: 'combobox:empty',
  WINDOWSPLITTER_CHANGE: 'windowsplitter:change',
  CALENDAR_CHANGE: 'calendar:change',
  TABS_BEFORE_ACTIVATE: 'tabs:before-activate',
  TABS_ACTIVATE: 'tabs:activate',
  TABS_DELETE: 'tabs:delete',
  CART_BEFORE_ADD: 'cart:before-add',
  CART_BEFORE_UPDATE: 'cart:before-update',
  CART_UPDATE: 'cart:update',
  VARIANT_CHANGE: 'variant:change',
};

export type EventNames = typeof EVENTS[keyof typeof EVENTS];
